# Utiliser l'image Node.js
FROM node:22

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers
COPY package*.json ./
RUN npm install --omit=dev
RUN npm rebuild bcrypt --build-from-source

# Copier le reste
COPY . .

# Commande par défaut
CMD ["node", "index.js"]
