services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

  chat-service:
    build:
      context: ./chat-service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./chat-service:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
